### ISSUE TITLE
1.17 Support?

### ISSUE THREAD

**Issue by VanillaChan6571** [scruffyboy13/Economy#4]
Tried this plugin with 1.17 seems to not get uuid's correctly..

```
[17.06 08:45:21.441] INFO: [Survival-1] [08:45:20] [Craft Scheduler Thread - 11/WARN]: [Economy] Plugin Economy v2.2 generated an exception while executing task 8
[17.06 08:45:21.441] INFO: [Survival-1] java.lang.NullPointerException: Cannot invoke "String.length()" because "name" is null
[17.06 08:45:21.441] INFO: [Survival-1]       at java.util.UUID.fromString(UUID.java:237) ~[?:?]
[17.06 08:45:21.441] INFO: [Survival-1]       at me.scruffyboy13.Economy.eco.YamlEconomy.getPlayers(YamlEconomy.java:98) ~[?:?]
[17.06 08:45:21.441] INFO: [Survival-1]       at me.scruffyboy13.Economy.runnables.BalanceTopRunnable.run(BalanceTopRunnable.java:19) ~[?:?]
[17.06 08:45:21.441] INFO: [Survival-1]       at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[tuinity.jar:3147-Spigot-9472b09-d7ef1e9]
[17.06 08:45:21.441] INFO: [Survival-1]       at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [tuinity.jar:3147-Spigot-9472b09-d7ef1e9]
[17.06 08:45:21.441] INFO: [Survival-1]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
[17.06 08:45:21.441] INFO: [Survival-1]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
[17.06 08:45:21.441] INFO: [Survival-1]       at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by akrentz6** [comment]
This doesn't seem to be a problem with the plugin working on 1.17 but a problem with your data files, can you 'start a conversation' on https://www.spigotmc.org/members/scruffyboy12.707126/ so that i can help you fix it.
